"""add to model User change roles from enum to string

Revision ID: baabec45a5bb
Revises: 5826c588b795
Create Date: 2025-12-05 18:41:42.485358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baabec45a5bb'
down_revision: Union[str, Sequence[str], None] = '5826c588b795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'admin', name='userrole'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('user', 'admin', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###
